### PR TITLE
Update webpack, add missing vue.config.js, fix minor vue bugs

### LINKED ISSUE #30691: npm run build fails in both node 14 & 16 with ps_buybuttonlite module
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are incompatible issues between node-sass, sass-loader and Node in current [dev package.json](https://github.com/PrestaShop/ps_buybuttonlite/blob/dev/app/package.json) that make `npm run build` fail.
With Node 14:
ps_buybuttonlite_node14_node-sass-v7_incompatible_with_loader-4 0 0
With Node 16:
ps_buybuttonlite_node16_node-sass-v7_incompatible

### Expected behavior

`npm run build` succeed in Node 14 and/or Node 16

### Steps to reproduce

1. git clone ps_buybuttonlite
2. `cd modules/ps_buybuttonlite/app`
3. switch to Node 14 or Node 16 with `nvm`, then
`npm install`, `npm run build`
to see the errors.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_buybuttonlite 1.0.1

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | downgrade node-sass to 6 to keep it compatible with Node 14 like other dependencies <br> remove Addons Marketplace widget
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#30691
| How to test?  | In Terminal, `cd modules/ps_buybuttonlite/app`, then `nvm use 14`, `npm install`, `npm run build`. <br /> In Back-Office, check if module works as usual (don't forget to clear browser cache as well as run BO's clear cache :)

### CODE REVIEW

**Comment by NeOMakinG** [comment]
@leemyongpakvn Did you try to switch to `sass-embedded` in order to be compatible with node 14-16-18-19 with increased performances? Could be cool, we did the switch on a lot of repositories

**Comment by leemyongpakvn** [comment]
@NeOMakinG No, I didn't. This is my first change on Node, Vue and Webpack, so I tried to upgrade, not migrate. I will consider  sass-embeded switch on this module after your [related PR](https://github.com/PrestaShop/PrestaShop/pull/29842)  merged :)

**Comment by NeOMakinG** [comment]
> @NeOMakinG No, I didn't. This is my first change on Node, Vue and Webpack, so I tried to upgrade, not migrate. I will consider sass-embeded switch on this module after your [related PR](https://github.com/PrestaShop/PrestaShop/pull/29842) merged :)

This one is the last one, `default`, `core.js`, `classic` and `hummingbird` are already using sass-embedded If I'm not wrong

**Comment by leemyongpakvn** [comment]
@NeOMakinG You are above half-right. For themes: FO hummingbird and BO <s>new-theme</s> default are using sass-embedded while FO classic-theme and BO <s>default</s> new-theme are still using node-sass. Since  node-sass team also noted [Warning: LibSass and Node Sass are deprecated](https://github.com/sass/node-sass), I tried running `npm run build` for this module app with
```
    "sass-embedded": "^1.49.7",
    "sass-loader": "^12.6.0",
```
in both Node 14 and Node 16 and got
ps_buybutton_sass-embedded_node_14_16_failed
Building in Node 17 or Node 18 can help to solve _Node Sass incompatible_ issue but face another one _unsupported crypto/hash_ 
ps_buybutton_sass-embeded_failed_node_17_18

**Comment by NeOMakinG** [comment]
> @NeOMakinG You are above half-right. For themes: FO hummingbird and BO new-theme are using sass-embedded while FO classic-theme and BO default are still using node-sass. Since node-sass team also noted [Warning: LibSass and Node Sass are deprecated](https://github.com/sass/node-sass), I tried running `npm run build` for this module app with
> 
> ```
>     "sass-embedded": "^1.49.7",
>     "sass-loader": "^12.6.0",
> ```
> 
> in both Node 14 and Node 16 and got ps_buybutton_sass-embedded_node_14_16_failed Building in Node 17 or Node 18 can help to solve _Node Sass incompatible_ issue but face another one _unsupported crypto/hash_ ps_buybutton_sass-embeded_failed_node_17_18

Might be a lot of work or a bit more, but I guess updating `mini-css-extract-plugin` and upgrading to Vue 3 would fix almost everything from the screen you gave if you want to give it a try, or just leave it for the future!

**Comment by leemyongpakvn** [comment]
@NeOMakinG The latest element-ui 2.15.12  is still [incompatible with Vue 3](https://github.com/ElemeFE/element/blob/v2.15.12/package.json#L140) so let's leave sass-embedded switch and Vue 3 upgrade in a future PR.

**Pull request closed without merging**
