### PR TITLE
Improve call to `implode()` for php7.4

### PR DESCRIPTION
**Pull request by MathiasReker**

### CODE REVIEW

**Comment by Progi1984** [comment]
@MathiasReker Are you sure ? That change completly the behavior.

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
@Progi1984 Look at the documentation: https://www.php.net/implode
The change is legit, the old behavior should not working as well :/

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PierreRambaud The problem is that we have no scenario for testing ;)

**Comment by matks** [comment]
Hello @PierreRambaud @Progi1984 is that another situation where ; with 7.4, when using `implode` method, the separator must come before the array? Like https://github.com/PrestaShop/PrestaShop/pull/24479/

If yes I agree with @PierreRambaud . As change is supposed to be transparent for end user, one way to handle it would be we merge it as we expect no unexpected side effects, and we know that next ps_buybuttonlite version will be tested by QA, so this change will be tested as well.

**Review by matks — APPROVED** [review]

**Comment by PierreRambaud** [comment]
I already tested it on the Core with the @matthieu-rolland 's PR. There is nothing for the QA and it can be merged.

**Comment by PierreRambaud** [comment]
Thank you @MathiasReker

**Pull request merged**
